create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  birthdate date,
  city text,
  bio text,
  avatar_url text,
  verified boolean not null default false,
  credits integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.likes (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(sender_id, receiver_id),
  check (sender_id <> receiver_id)
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique(user_a,user_b),
  check (user_a <> user_b)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  starts_at timestamptz not null,
  city text,
  venue text,
  latitude double precision,
  longitude double precision,
  image_url text,
  price_cents integer not null default 0,
  capacity integer,
  created_at timestamptz not null default now()
);
alter table public.events add column if not exists latitude double precision;
alter table public.events add column if not exists longitude double precision;
alter table public.events add column if not exists image_url text;

create table if not exists public.event_bookings (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  stripe_checkout_session_id text unique,
  payment_status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(event_id,user_id)
);

create table if not exists public.credit_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  reason text not null,
  stripe_checkout_session_id text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.live_locations (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m integer,
  visibility text not null default 'matches' check (visibility in ('matches','friends')),
  precise boolean not null default false,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.likes enable row level security;
alter table public.matches enable row level security;
alter table public.messages enable row level security;
alter table public.events enable row level security;
alter table public.event_bookings enable row level security;
alter table public.credit_transactions enable row level security;
alter table public.live_locations enable row level security;

create policy "profiles readable by signed in users" on public.profiles for select to authenticated using (true);
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "users insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);

create policy "users read likes involving them" on public.likes for select to authenticated using (auth.uid() in (sender_id,receiver_id));
create policy "users insert own likes" on public.likes for insert to authenticated with check (auth.uid()=sender_id);
create policy "participants read matches" on public.matches for select to authenticated using (auth.uid() in (user_a,user_b));
create policy "participants read messages" on public.messages for select to authenticated using (exists (select 1 from public.matches m where m.id=match_id and m.status='active' and auth.uid() in (m.user_a,m.user_b)));
create policy "participants send messages" on public.messages for insert to authenticated with check (auth.uid() = sender_id and exists (select 1 from public.matches m where m.id=match_id and m.status='active' and auth.uid() in (m.user_a,m.user_b)));

create policy "events are public to signed in users" on public.events for select to authenticated using (true);
create policy "users read own bookings" on public.event_bookings for select to authenticated using (auth.uid()=user_id);
create policy "users insert own pending bookings" on public.event_bookings for insert to authenticated with check (auth.uid()=user_id and payment_status='pending');
create policy "users read own transactions" on public.credit_transactions for select to authenticated using (auth.uid()=user_id);

create policy "users manage own live location" on public.live_locations for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "matched users can read live locations" on public.live_locations for select to authenticated using (
  expires_at > now() and exists (
    select 1 from public.matches m
    where m.status='active'
      and ((m.user_a=auth.uid() and m.user_b=live_locations.user_id) or (m.user_b=auth.uid() and m.user_a=live_locations.user_id))
  )
);

create or replace function public.send_like(target_user uuid)
returns table(matched boolean, match_id uuid, credits_left integer)
language plpgsql security definer set search_path=public as $$
declare
  me uuid := auth.uid();
  my_credits integer;
  reciprocal boolean;
  a uuid;
  b uuid;
  mid uuid;
begin
  if me is null then raise exception 'Not authenticated'; end if;
  if target_user is null or target_user=me then raise exception 'Invalid target'; end if;
  if not exists(select 1 from profiles where id=target_user) then raise exception 'Profile not found'; end if;

  if exists(select 1 from likes where sender_id=me and receiver_id=target_user) then
    select credits into my_credits from profiles where id=me;
  else
    select credits into my_credits from profiles where id=me for update;
    if coalesce(my_credits,0) < 1 then raise exception 'Not enough credits'; end if;
    update profiles set credits=credits-1, updated_at=now() where id=me;
    insert into likes(sender_id,receiver_id) values(me,target_user);
    insert into credit_transactions(user_id,amount,reason) values(me,-1,'like');
    my_credits := my_credits - 1;
  end if;

  select exists(select 1 from likes where sender_id=target_user and receiver_id=me) into reciprocal;
  if reciprocal then
    a := least(me,target_user); b := greatest(me,target_user);
    insert into matches(user_a,user_b,status) values(a,b,'active') on conflict(user_a,user_b) do update set status='active' returning id into mid;
    return query select true, mid, my_credits;
  else
    return query select false, null::uuid, my_credits;
  end if;
end; $$;
grant execute on function public.send_like(uuid) to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name, credits)
  values(new.id, coalesce(new.raw_user_meta_data->>'display_name',''), 3)
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.matches;
exception when duplicate_object then null; end $$;
