create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  birthdate date,
  city text,
  bio text,
  avatar_url text,
  verified boolean not null default false,
  credits integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique(user_a,user_b)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  starts_at timestamptz not null,
  city text,
  venue text,
  price_cents integer not null default 0,
  capacity integer,
  created_at timestamptz not null default now()
);

create table if not exists public.event_bookings (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  stripe_checkout_session_id text unique,
  payment_status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(event_id,user_id)
);

create table if not exists public.credit_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  reason text not null,
  stripe_checkout_session_id text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.messages enable row level security;
alter table public.events enable row level security;
alter table public.event_bookings enable row level security;
alter table public.credit_transactions enable row level security;

create policy "profiles readable by signed in users" on public.profiles for select to authenticated using (true);
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "users insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);

create policy "participants read matches" on public.matches for select to authenticated using (auth.uid() in (user_a,user_b));
create policy "participants read messages" on public.messages for select to authenticated using (exists (select 1 from public.matches m where m.id=match_id and auth.uid() in (m.user_a,m.user_b)));
create policy "participants send messages" on public.messages for insert to authenticated with check (auth.uid() = sender_id and exists (select 1 from public.matches m where m.id=match_id and auth.uid() in (m.user_a,m.user_b)));

create policy "events are public to signed in users" on public.events for select to authenticated using (true);
create policy "users read own bookings" on public.event_bookings for select to authenticated using (auth.uid()=user_id);
create policy "users read own transactions" on public.credit_transactions for select to authenticated using (auth.uid()=user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name, credits)
  values(new.id, coalesce(new.raw_user_meta_data->>'display_name',''), 3)
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
