import { useEffect, useState } from 'react'
import { backendConfigured } from './lib/supabase'
import { getSession, onAuthChange, signIn, signOut, signUp, startCheckout, shareLiveLocation, stopLiveLocation, listVisibleLiveLocations } from './lib/backend'

const intents = [['♡','Date'],['♧','Drink'],['🍴','Dinner'],['♫','Music'],['✣','Move'],['☆','Party'],['✈','Trip'],['♨','Chill'],['●','Event'],['◌','Explore'],['⚽','Sport'],['+','Andere']]
const times = ['Jetzt · In den nächsten 2 Stunden','Heute Abend · Ab 18:00','Dieses Wochenende · Sa–So','Irgendwann · Passt mir zusammen']
const matchTypes = [['ONE','Jemand Besonderes','Date / romantisch'],['2','Neue Freunde','Locker kennenlernen'],['US','Eine Gruppe','Gemeinsam ist besser']]
const people = [
{name:'Mara',age:34,match:96,city:'Hamburg',bio:'Konzerte, gute Drinks und spontane Wochenenden.',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=85'},
{name:'Tim',age:36,match:92,city:'Lübeck',bio:'Sportlich, neugierig, gern draußen.',img:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=85'},
{name:'Lea',age:33,match:91,city:'Hamburg',bio:'Foodie, Reisen, Live-Musik.',img:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=85'},
{name:'Max',age:35,match:89,city:'Kiel',bio:'Bars, Fußball, Meer.',img:'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&w=700&q=85'},
{name:'Sara',age:32,match:88,city:'Lübeck',bio:'Kunst, Wein und gute Gespräche.',img:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=700&q=85'},
{name:'Ben',age:37,match:86,city:'Hamburg',bio:'Running, Reisen, Streetfood.',img:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=85'}]
const experiences = [
{title:'Cocktail Night',meta:'Heute · 19:30 · Lübeck',price:19,distance:'850 m',img:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85'},
{title:'Live Konzert',meta:'Heute · 20:00 · Hamburg',price:24,distance:'2,1 km',img:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=85'},
{title:'Running Crew',meta:'Morgen · 09:00 · Lübeck',price:9,distance:'1,4 km',img:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=85'}]
const heroPhotos=['https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=700&q=85']
function Logo({compact=false,hero=false}) { return <div className={'logo '+(compact?'compact ':'')+(hero?'hero-logo':'')}><span>One</span><i>:</i><b>2</b><i>:</i><span>Us</span></div> }

export default function App(){
 const [screen,setScreen]=useState('welcome'); const [intent,setIntent]=useState('Date'); const [time,setTime]=useState(times[1]); const [type,setType]=useState('ONE'); const [credits,setCredits]=useState(12); const [toast,setToast]=useState(''); const [checkout,setCheckout]=useState(null); const [selectedPerson,setSelectedPerson]=useState(null); const [chatText,setChatText]=useState(''); const [chat,setChat]=useState([{from:'them',text:'Hey! Lust heute Abend auf einen Drink?'}])
 const [session,setSession]=useState(null); const [authReady,setAuthReady]=useState(!backendConfigured); const [authMode,setAuthMode]=useState('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [displayName,setDisplayName]=useState(''); const [authBusy,setAuthBusy]=useState(false); const [authError,setAuthError]=useState('')
 const [geo,setGeo]=useState(null); const [geoBusy,setGeoBusy]=useState(false); const [geoError,setGeoError]=useState(''); const [sharing,setSharing]=useState(false); const [precise,setPrecise]=useState(false); const [visibility,setVisibility]=useState('matches'); const [livePeople,setLivePeople]=useState([])
 useEffect(()=>{ if(!backendConfigured)return; getSession().then(s=>{setSession(s);setAuthReady(true)}); const sub=onAuthChange(s=>setSession(s)); return()=>sub.unsubscribe() },[])
 const flash=m=>{setToast(m);setTimeout(()=>setToast(''),2000)}
 const handleAuth=async()=>{setAuthBusy(true);setAuthError('');try{if(authMode==='register'){await signUp(email,password,displayName);flash('Account angelegt.')}else await signIn(email,password)}catch(e){setAuthError(e.message)}finally{setAuthBusy(false)}}
 const pay=async(label,amount)=>{ if(label.includes('Credits')&&backendConfigured&&session){try{await startCheckout('credits',amount)}catch(e){flash(e.message)}return} setCheckout({label,amount}) }
 const confirmPay=()=>{setCredits(v=>v+checkout.amount);flash(`${checkout.amount} Credits gekauft`);setCheckout(null)}
 const sendChat=()=>{if(!chatText.trim())return;setChat(v=>[...v,{from:'me',text:chatText.trim()}]);setChatText('')}
 const locateMe=()=>{setGeoBusy(true);setGeoError('');if(!navigator.geolocation){setGeoError('Standort wird von diesem Gerät nicht unterstützt.');setGeoBusy(false);return}navigator.geolocation.getCurrentPosition(pos=>{setGeo({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy});setGeoBusy(false);flash('Standort gefunden')},err=>{setGeoError(err.code===1?'Standortfreigabe wurde nicht erlaubt.':'Standort konnte nicht ermittelt werden.');setGeoBusy(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
 const startSharing=async()=>{if(!geo){locateMe();return}try{if(backendConfigured)await shareLiveLocation({...geo,visibility,precise,minutes:30});setSharing(true);flash('Live-Standort für 30 Min. aktiv')}catch(e){setSharing(true);flash('Live-Modus lokal aktiv – Datenbank-Update noch ausstehend')}}
 const stopSharing=async()=>{try{if(backendConfigured)await stopLiveLocation()}catch{}setSharing(false);flash('Live-Standort beendet')}
 const refreshLive=async()=>{try{const rows=backendConfigured?await listVisibleLiveLocations():[];setLivePeople(rows)}catch{setLivePeople([])}}
 useEffect(()=>{if(screen==='live')refreshLive()},[screen])
 if(!authReady) return <div className="app-shell"><main className="phone"><div className="auth-card"><Logo compact/><p>Verbindung wird hergestellt …</p></div></main></div>
 if(backendConfigured&&!session) return <div className="app-shell"><main className="phone"><div className="auth-card"><Logo compact/><h1>{authMode==='login'?'Willkommen zurück.':'From me to we.'}</h1><p>{authMode==='login'?'Einloggen und echte Verbindungen finden.':'Erstelle dein One:2:Us Profil.'}</p>{authMode==='register'&&<input placeholder="Dein Name" value={displayName} onChange={e=>setDisplayName(e.target.value)}/>}<input type="email" placeholder="E-Mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Passwort (mind. 6 Zeichen)" value={password} onChange={e=>setPassword(e.target.value)}/>{authError&&<small className="auth-error">{authError}</small>}<button className="primary" disabled={authBusy} onClick={handleAuth}>{authBusy?'Bitte warten …':authMode==='login'?'Einloggen':'Registrieren'}</button><button className="auth-switch" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'Noch kein Konto? Registrieren':'Schon dabei? Einloggen'}</button></div></main></div>
 return <div className="app-shell"><main className="phone">
  <header className="topbar"><Logo/><button className="credit-pill" onClick={()=>setScreen('wallet')}>● {credits}</button></header>
  <section className="content">
   {screen==='welcome'&&<div className="welcome"><div className="hero"><img src={heroPhotos[0]}/><div className="hero-shade"></div><div className="hero-brand"><Logo hero/><span>MEET BEYOND MATCHING.</span></div><div className="hero-copy"><span className="eyebrow">ECHT. SPONTAN. ZUSAMMEN.</span><h1>From me<br/>to <em>we.</em></h1><p>Dating, Freundschaft und gemeinsame Erlebnisse in einer App. Nicht ewig swipen – sondern rausgehen.</p></div></div><div className="welcome-actions"><button className="primary" onClick={()=>setScreen('home')}>Was willst du heute? →</button><div className="mini-gallery"><img src={heroPhotos[1]}/><div><b>Mehr echte Momente.</b><span>Vom Drink zu zweit bis zur spontanen Gruppe.</span></div><img src={heroPhotos[2]}/></div><div className="manifesto"><span>ONE</span><i>für dich</i><span>2</span><i>mit jemandem</i><span>US</span><i>gemeinsam</i></div><p className="promise">Keine endlosen Swipes. Kein Abo-Zwang. Entscheide, was du erleben willst – und finde Menschen, die dazu passen.</p></div></div>}
   {screen==='home'&&<><div className="hello"><h1>Hey {session?.user?.user_metadata?.display_name || 'Leon'}! 👋</h1><p>Was willst du heute?</p></div><button className="nearby-banner" onClick={()=>setScreen('live')}><span>◎</span><div><b>Live in deiner Nähe</b><small>Events & Matches auf der Karte entdecken</small></div><strong>→</strong></button><div className="intent-grid">{intents.map(([ic,n])=><button className={intent===n?'selected':''} key={n} onClick={()=>setIntent(n)}><span>{ic}</span>{n}</button>)}</div><h4>ONE, 2 oder US?</h4><div className="mode-grid"><button className={type==='ONE'?'one active':'one'} onClick={()=>setType('ONE')}><b>ONE</b><small>Für mich</small></button><button className={type==='2'?'two active':'two'} onClick={()=>setType('2')}><b>2</b><small>Mit jemandem</small></button><button className={type==='US'?'us active':'us'} onClick={()=>setType('US')}><b>US</b><small>In einer Gruppe</small></button></div><button className="primary" onClick={()=>setScreen('time')}>Weiter</button></>}
   {screen==='live'&&<><div className="page-title"><h1>Live Map</h1><p>Finde Events in deiner Umgebung und – nur mit gegenseitiger Freigabe – deine Matches.</p></div><div className="live-map"><div className="map-grid"></div><div className="map-you">●<span>Du</span></div><div className="map-pin event one">♫<span>Live Konzert</span></div><div className="map-pin event two">🍸<span>Cocktail Night</span></div><div className="map-pin person">♡<span>Match live</span></div><div className="map-status">{geo?`Standort aktiv · ± ${Math.round(geo.accuracy)} m`:'Standort noch nicht aktiviert'}</div></div>{geoError&&<div className="location-error">{geoError}</div>}<button className="secondary" onClick={locateMe} disabled={geoBusy}>{geoBusy?'Standort wird gesucht …':'◎ Meinen Standort verwenden'}</button><div className="privacy-card"><div><b>Live-Standort teilen</b><p>Standardmäßig AUS. Nur aktive Matches können dich sehen. Die Freigabe endet automatisch nach 30 Minuten.</p></div><label className="toggle"><input type="checkbox" checked={sharing} onChange={e=>e.target.checked?startSharing():stopSharing()}/><span></span></label><div className="live-options"><label><input type="checkbox" checked={precise} onChange={e=>setPrecise(e.target.checked)}/> Präzisen Standort zeigen</label><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="matches">Nur Matches</option><option value="friends">Nur Freunde</option></select></div></div><h3 className="section-title">Events in deiner Nähe</h3><div className="nearby-list">{experiences.map(e=><button key={e.title} onClick={()=>{setSelectedPerson(e);setScreen('event')}}><img src={e.img}/><div><b>{e.title}</b><span>{e.meta}</span><small>◎ {e.distance}</small></div><strong>{e.price} €</strong></button>)}</div><h3 className="section-title">Live sichtbar</h3><div className="live-note">{livePeople.length?`${livePeople.length} freigegebene Kontakte sind gerade sichtbar.`:'Noch keine gegenseitig freigegebenen Live-Standorte. Die Funktion zeigt nur Personen, die ihre Position ausdrücklich teilen.'}</div></>}
   {screen==='time'&&<><div className="page-title"><h1>Wann?</h1><p>Sag uns, wann es passt.</p></div><div className="choice-list">{times.map(t=><button className={time===t?'active':''} onClick={()=>setTime(t)} key={t}>{t}</button>)}</div><button className="primary" onClick={()=>setScreen('type')}>Weiter</button></>}
   {screen==='type'&&<><div className="page-title"><h1>Mit wem?</h1><p>Wer passt zu dir?</p></div><div className="choice-list">{matchTypes.map(([k,a,b])=><button className={type===k?'active':''} onClick={()=>setType(k)} key={k}><strong>{k}</strong><span><b>{a}</b><small>{b}</small></span></button>)}</div><button className="primary" onClick={()=>setScreen('matches')}>Matches finden · 1 Credit</button></>}
   {screen==='matches'&&<><div className="page-title"><h1>Deine Matches</h1><p>Menschen, die zu {intent} und deinem Timing passen.</p></div><div className="people-grid rich">{people.map(p=><button key={p.name} onClick={()=>{setSelectedPerson(p);setScreen('person')}}><img src={p.img}/><div><b>{p.name}, {p.age}</b><small>{p.city}</small><strong>{p.match}% Match</strong></div></button>)}</div></>}
   {screen==='person'&&selectedPerson&&<><div className="person-hero"><img src={selectedPerson.img}/><button onClick={()=>setScreen('matches')}>←</button><div><h1>{selectedPerson.name}, {selectedPerson.age}</h1><p>{selectedPerson.city} · {selectedPerson.match}% Match</p></div></div><div className="person-copy"><p>{selectedPerson.bio}</p><div className="tag-row"><span>{intent}</span><span>{time.split(' · ')[0]}</span><span>{type}</span></div><button className="primary" onClick={()=>{if(credits<1)return setScreen('wallet');setCredits(v=>v-1);flash('Like gesendet');setScreen('chat')}}>Like senden · 1 Credit</button></div></>}
   {screen==='chat'&&<><div className="page-title"><h1>{selectedPerson?.name || 'Chat'}</h1><p>Nach dem Match ist der Chat kostenlos.</p></div><div className="chat-box">{chat.map((m,i)=><div key={i} className={'bubble '+m.from}>{m.text}</div>)}</div><div className="chat-input"><input value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Nachricht schreiben …"/><button onClick={sendChat}>↑</button></div></>}
   {screen==='experiences'&&<><div className="page-title"><h1>Vorschläge für dich</h1><p>{intent} · {time.split(' · ')[0]}</p></div><div className="experience-list rich">{experiences.map(e=><button key={e.title} onClick={()=>{setSelectedPerson(e);setScreen('event')}}><img src={e.img}/><span><b>{e.title}</b><small>{e.meta}</small></span><strong>{e.price} €</strong></button>)}</div></>}
   {screen==='event'&&<><div className="event-cover photo" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.75)),url(${selectedPerson?.img||experiences[0].img})`}}><span>ONE NIGHT</span></div><div className="event-detail"><h1>{selectedPerson?.title||'Cocktail Night'}</h1><p>{selectedPerson?.meta||'Heute · 19:30 · Lübeck'}</p><p>Menschen mit ähnlichen Interessen sind bereits dabei.</p><button className="primary" onClick={()=>pay(`${selectedPerson?.title||'Cocktail Night'} Ticket`,selectedPerson?.price||19)}>Ich bin dabei! · {selectedPerson?.price||19} €</button></div></>}
   {screen==='wallet'&&<><div className="page-title"><h1>Pay per use.</h1><p>Kein Abo. Du zahlst nur, wenn du One:2:Us nutzt.</p></div><div className="balance"><small>Dein Guthaben</small><strong>{credits}</strong><span>Credits</span></div><div className="packs">{[[10,9.9],[25,19.9],[60,39.9]].map(([c,p])=><button key={c} onClick={()=>pay(`${c} Credits`,c)}><b>{c} Credits</b><span>{p.toFixed(2).replace('.',',')} €</span></button>)}</div><div className="payment-note"><b>Sichere Zahlung</b><p>Apple Pay · Google Pay · Karte</p><small>Stripe Checkout ist vorbereitet. Sobald die Edge Function konfiguriert ist, laufen Käufe serverseitig.</small></div></>}
   {screen==='profile'&&<><div className="page-title"><h1>Profil</h1><p>Dein Auftritt entscheidet über gute Matches.</p></div><div className="profile-box"><div className="profile-avatar">{(session?.user?.user_metadata?.display_name || 'L')[0]}</div><h2>{session?.user?.user_metadata?.display_name || 'Leon'}</h2><p>{session?'Account aktiv ✓':'Demo-Profil'}</p>{session&&<button className="primary" onClick={signOut}>Ausloggen</button>}</div><div className="choice-list"><button>Profilbild & Bio ›</button><button>Interessen & Präferenzen ›</button><button onClick={()=>setScreen('live')}>Live-Standort & Sichtbarkeit ›</button><button>Sicherheit & Verifizierung ›</button><button>Datenschutz ›</button></div></>}
  </section>
  <nav className="nav five"><button className={['welcome','home'].includes(screen)?'active':''} onClick={()=>setScreen('welcome')}>⌂<span>Home</span></button><button className={['time','type','matches','person','experiences','event'].includes(screen)?'active':''} onClick={()=>setScreen('matches')}>⌕<span>Entdecken</span></button><button className={screen==='live'?'active':''} onClick={()=>setScreen('live')}>◎<span>Live</span></button><button className={screen==='chat'?'active':''} onClick={()=>setScreen('chat')}>♡<span>Chats</span></button><button className={screen==='profile'?'active':''} onClick={()=>setScreen('profile')}>♙<span>Profil</span></button></nav>
  {checkout&&<div className="modal"><div><Logo compact/><h2>{checkout.label}</h2><p>{checkout.amount===19?'19,00 €':'Credit-Paket kaufen'}</p><button className="apple" onClick={confirmPay}> Pay</button><button className="card" onClick={confirmPay}>Mit Karte bezahlen</button><button className="cancel" onClick={()=>setCheckout(null)}>Abbrechen</button><small>Demo-Zahlung, solange Stripe noch nicht final verbunden ist.</small></div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main></div>
}