import { useEffect, useRef, useState } from 'react'
import { backendConfigured } from './lib/supabase'
import {
  getSession, onAuthChange, signIn, signOut, signUp, startCheckout,
  shareLiveLocation, stopLiveLocation, listVisibleLiveLocations,
  getMyProfile, listProfiles, sendLike, listMatches, subscribeMatches,
  listEvents, listMyBookings, loadMessages, subscribeMessages, sendMessage,
  markMessagesRead, createTypingChannel
} from './lib/backend'

const intents = [['♡','Date'],['♧','Drink'],['🍴','Dinner'],['♫','Music'],['✣','Move'],['☆','Party'],['✈','Trip'],['♨','Chill'],['●','Event'],['◌','Explore'],['⚽','Sport'],['+','Andere']]
const times = ['Jetzt · In den nächsten 2 Stunden','Heute Abend · Ab 18:00','Dieses Wochenende · Sa–So','Irgendwann · Passt mir zusammen']
const matchTypes = [['ONE','Jemand Besonderes','Date / romantisch'],['2','Neue Freunde','Locker kennenlernen'],['US','Eine Gruppe','Gemeinsam ist besser']]
const fallbackPeople = [
{name:'Mara',age:34,match:96,city:'Hamburg',bio:'Konzerte, gute Drinks und spontane Wochenenden.',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=85'},
{name:'Tim',age:36,match:92,city:'Lübeck',bio:'Sportlich, neugierig, gern draußen.',img:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=85'},
{name:'Lea',age:33,match:91,city:'Hamburg',bio:'Foodie, Reisen, Live-Musik.',img:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=85'},
{name:'Max',age:35,match:89,city:'Kiel',bio:'Bars, Fußball, Meer.',img:'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&w=700&q=85'},
{name:'Sara',age:32,match:88,city:'Lübeck',bio:'Kunst, Wein und gute Gespräche.',img:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=700&q=85'},
{name:'Ben',age:37,match:86,city:'Hamburg',bio:'Running, Reisen, Streetfood.',img:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=85'}]
const fallbackEvents = [
{title:'Cocktail Night',meta:'Heute · 19:30 · Lübeck',price:19,distance:'850 m',img:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85'},
{title:'Live Konzert',meta:'Heute · 20:00 · Hamburg',price:24,distance:'2,1 km',img:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=85'},
{title:'Running Crew',meta:'Morgen · 09:00 · Lübeck',price:9,distance:'1,4 km',img:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=85'}]
const heroPhotos=['https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=700&q=85']
const fallbackAvatar='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=85'
function Logo({compact=false,hero=false}) { return <div className={'logo '+(compact?'compact ':'')+(hero?'hero-logo':'')}><span>One</span><i>:</i><b>2</b><i>:</i><span>Us</span></div> }
function ageFromBirthdate(value){ if(!value)return null; const d=new Date(value); const n=new Date(); let age=n.getFullYear()-d.getFullYear(); if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))age--; return age }
function kmBetween(a,b){ if(!a||!b||b.latitude==null||b.longitude==null)return null; const r=6371,toRad=x=>x*Math.PI/180; const dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude); const la1=toRad(a.latitude),la2=toRad(b.latitude); const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2; return 2*r*Math.asin(Math.sqrt(h)) }
function formatDistance(km){ if(km==null)return null; return km<1?`${Math.max(50,Math.round(km*1000/50)*50)} m`:`${km.toFixed(km<10?1:0).replace('.',',')} km` }
function chatTime(value){ if(!value)return ''; return new Date(value).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}) }

export default function App(){
 const [screen,setScreen]=useState('welcome'); const [intent,setIntent]=useState('Date'); const [time,setTime]=useState(times[1]); const [type,setType]=useState('ONE'); const [credits,setCredits]=useState(0); const [toast,setToast]=useState(''); const [checkout,setCheckout]=useState(null); const [selectedPerson,setSelectedPerson]=useState(null); const [selectedEvent,setSelectedEvent]=useState(null)
 const [session,setSession]=useState(null); const [authReady,setAuthReady]=useState(!backendConfigured); const [authMode,setAuthMode]=useState('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [displayName,setDisplayName]=useState(''); const [authBusy,setAuthBusy]=useState(false); const [authError,setAuthError]=useState('')
 const [profiles,setProfiles]=useState([]); const [matches,setMatches]=useState([]); const [events,setEvents]=useState([]); const [bookings,setBookings]=useState([]); const [activeMatch,setActiveMatch]=useState(null); const [chatText,setChatText]=useState(''); const [chat,setChat]=useState([]); const [backendBusy,setBackendBusy]=useState(false); const [otherTyping,setOtherTyping]=useState(false)
 const [geo,setGeo]=useState(null); const [geoBusy,setGeoBusy]=useState(false); const [geoError,setGeoError]=useState(''); const [sharing,setSharing]=useState(false); const [precise,setPrecise]=useState(false); const [visibility,setVisibility]=useState('matches'); const [livePeople,setLivePeople]=useState([])
 const watchRef=useRef(null); const shareTimerRef=useRef(null); const typingChannelRef=useRef(null); const typingStopRef=useRef(null)
 const flash=m=>{setToast(m);setTimeout(()=>setToast(''),2200)}

 useEffect(()=>{ if(!backendConfigured)return; getSession().then(s=>{setSession(s);setAuthReady(true)}); const sub=onAuthChange(s=>setSession(s)); return()=>sub.unsubscribe() },[])
 useEffect(()=>{ if(!session||!backendConfigured)return; refreshBackend(); const sub=subscribeMatches(()=>refreshMatches()); return()=>sub.unsubscribe() },[session])
 useEffect(()=>{ if(!session||!backendConfigured)return; const sync=()=>refreshBackend(); const onVisibility=()=>{if(document.visibilityState==='visible')sync()}; window.addEventListener('focus',sync); window.addEventListener('pageshow',sync); document.addEventListener('visibilitychange',onVisibility); return()=>{window.removeEventListener('focus',sync);window.removeEventListener('pageshow',sync);document.removeEventListener('visibilitychange',onVisibility)} },[session])
 useEffect(()=>{ if(!activeMatch?.id||!backendConfigured||!session?.user?.id)return; let alive=true; const refreshRead=()=>markMessagesRead(activeMatch.id).catch(()=>{}); loadMessages(activeMatch.id).then(rows=>{if(!alive)return;setChat(rows);refreshRead()}).catch(()=>{}); const sub=subscribeMessages(activeMatch.id,msg=>{setChat(v=>{const at=v.findIndex(x=>x.id===msg.id);if(at<0)return [...v,msg];const copy=[...v];copy[at]={...copy[at],...msg};return copy});if(msg.sender_id!==session.user.id)refreshRead()}); return()=>{alive=false;sub.unsubscribe()} },[activeMatch?.id,session?.user?.id])
 useEffect(()=>{ if(!activeMatch?.id||!session?.user?.id||!backendConfigured)return; setOtherTyping(false); const channel=createTypingChannel(activeMatch.id,session.user.id,setOtherTyping); typingChannelRef.current=channel; return()=>{channel.sendTyping(false);channel.unsubscribe();typingChannelRef.current=null;setOtherTyping(false)} },[activeMatch?.id,session?.user?.id])
 useEffect(()=>()=>{ if(watchRef.current!=null)navigator.geolocation?.clearWatch(watchRef.current); if(shareTimerRef.current)clearTimeout(shareTimerRef.current); if(typingStopRef.current)clearTimeout(typingStopRef.current) },[])

 const refreshBackend=async()=>{setBackendBusy(true);try{const me=await getMyProfile();if(me?.credits!=null)setCredits(me.credits);const results=await Promise.allSettled([listProfiles(),listMatches(),listEvents(),listMyBookings()]);if(results[0].status==='fulfilled')setProfiles(results[0].value);if(results[1].status==='fulfilled')setMatches(results[1].value);if(results[2].status==='fulfilled')setEvents(results[2].value);if(results[3].status==='fulfilled')setBookings(results[3].value);results.filter(r=>r.status==='rejected').forEach(r=>console.warn(r.reason))}catch(e){console.warn(e)}finally{setBackendBusy(false)}}
 const refreshMatches=async()=>{try{setMatches(await listMatches())}catch{}}
 const handleAuth=async()=>{setAuthBusy(true);setAuthError('');try{if(authMode==='register'){await signUp(email,password,displayName);flash('Account angelegt.')}else await signIn(email,password)}catch(e){setAuthError(e.message)}finally{setAuthBusy(false)}}
 const payCredits=async amount=>{try{await startCheckout('credits',amount)}catch(e){flash(e.message)}}
 const buyEvent=async event=>{ if(event?.id&&backendConfigured){try{await startCheckout('event',event.id)}catch(e){flash(e.message)}return} setCheckout({label:`${event?.title||'Event'} Ticket`,amount:event?.price||19}) }
 const confirmPay=()=>{flash('Demo-Zahlung bestätigt');setCheckout(null)}

 const discoveryPeople=profiles.length?profiles.map((p,i)=>({id:p.id,name:p.display_name||'One:2:Us User',age:ageFromBirthdate(p.birthdate)||'',match:Math.max(78,96-i*3),city:p.city||'In deiner Nähe',bio:p.bio||'Offen für neue Begegnungen und gemeinsame Erlebnisse.',img:p.avatar_url||fallbackPeople[i%fallbackPeople.length].img,verified:p.verified})):fallbackPeople
 const visibleEvents=events.length?events.map(e=>({id:e.id,title:e.title,meta:`${new Date(e.starts_at).toLocaleString('de-DE',{weekday:'short',hour:'2-digit',minute:'2-digit'})} · ${e.city||e.venue||'In deiner Nähe'}`,price:(e.price_cents||0)/100,distance:formatDistance(kmBetween(geo,e)),img:e.image_url||fallbackEvents[0].img,description:e.description,latitude:e.latitude,longitude:e.longitude})):fallbackEvents

 const doLike=async()=>{if(!selectedPerson)return;if(!selectedPerson.id){flash('Demo-Profil – für echte Likes braucht es einen zweiten Testnutzer.');return}try{const result=await sendLike(selectedPerson.id);if(result.credits_left!=null)setCredits(result.credits_left);if(result.matched){await refreshMatches();const fresh=await listMatches();const m=fresh.find(x=>x.id===result.match_id)||fresh.find(x=>x.person?.id===selectedPerson.id);setActiveMatch(m||{id:result.match_id,person:selectedPerson});flash('It’s a Match! 🎉');setScreen('chat')}else{flash('Like gesendet – bei Gegenlike entsteht automatisch ein Match.');setScreen('matches')}}catch(e){if(String(e.message).toLowerCase().includes('credit'))setScreen('wallet');else flash(e.message)}}
 const openMatch=m=>{setActiveMatch(m);setSelectedPerson(m.person);setScreen('chat')}
 const handleChatInput=e=>{const value=e.target.value;setChatText(value);typingChannelRef.current?.sendTyping(!!value.trim());if(typingStopRef.current)clearTimeout(typingStopRef.current);typingStopRef.current=setTimeout(()=>typingChannelRef.current?.sendTyping(false),1200)}
 const sendChatNow=async()=>{const body=chatText.trim();if(!body)return;if(!activeMatch?.id){flash('Wähle zuerst ein echtes Match.');return}setChatText('');typingChannelRef.current?.sendTyping(false);try{await sendMessage(activeMatch.id,body)}catch(e){setChatText(body);flash(e.message)}}

 const locateMe=()=>{setGeoBusy(true);setGeoError('');if(!navigator.geolocation){setGeoError('Standort wird von diesem Gerät nicht unterstützt.');setGeoBusy(false);return}navigator.geolocation.getCurrentPosition(pos=>{setGeo({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy});setGeoBusy(false);flash('Standort gefunden')},err=>{setGeoError(err.code===1?'Standortfreigabe wurde nicht erlaubt.':'Standort konnte nicht ermittelt werden.');setGeoBusy(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:15000})}
 const startSharing=()=>{if(!navigator.geolocation){setGeoError('Standort wird nicht unterstützt.');return}if(watchRef.current!=null)navigator.geolocation.clearWatch(watchRef.current);setSharing(true);flash('Live-Standort für 30 Min. aktiv');watchRef.current=navigator.geolocation.watchPosition(async pos=>{const next={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy};setGeo(next);try{if(backendConfigured)await shareLiveLocation({...next,visibility,precise,minutes:30})}catch(e){setGeoError(e.message)}},err=>setGeoError(err.code===1?'Standortfreigabe wurde nicht erlaubt.':'Live-Standort konnte nicht aktualisiert werden.'),{enableHighAccuracy:true,timeout:15000,maximumAge:10000});if(shareTimerRef.current)clearTimeout(shareTimerRef.current);shareTimerRef.current=setTimeout(()=>stopSharing(),30*60*1000)}
 const stopSharing=async()=>{if(watchRef.current!=null){navigator.geolocation?.clearWatch(watchRef.current);watchRef.current=null}if(shareTimerRef.current){clearTimeout(shareTimerRef.current);shareTimerRef.current=null}try{if(backendConfigured)await stopLiveLocation()}catch{}setSharing(false);flash('Live-Standort beendet')}
 const refreshLive=async()=>{try{const rows=backendConfigured?await listVisibleLiveLocations():[];setLivePeople(rows)}catch{setLivePeople([])}}
 useEffect(()=>{if(screen==='live')refreshLive()},[screen])

 if(!authReady) return <div className="app-shell"><main className="phone"><div className="auth-card"><Logo compact/><p>Verbindung wird hergestellt …</p></div></main></div>
 if(backendConfigured&&!session) return <div className="app-shell"><main className="phone"><div className="auth-card"><Logo compact/><h1>{authMode==='login'?'Willkommen zurück.':'From me to we.'}</h1><p>{authMode==='login'?'Einloggen und echte Verbindungen finden.':'Erstelle dein One:2:Us Profil.'}</p>{authMode==='register'&&<input placeholder="Dein Name" value={displayName} onChange={e=>setDisplayName(e.target.value)}/>}<input type="email" placeholder="E-Mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Passwort (mind. 6 Zeichen)" value={password} onChange={e=>setPassword(e.target.value)}/>{authError&&<small className="auth-error">{authError}</small>}<button className="primary" disabled={authBusy} onClick={handleAuth}>{authBusy?'Bitte warten …':authMode==='login'?'Einloggen':'Registrieren'}</button><button className="auth-switch" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'Noch kein Konto? Registrieren':'Schon dabei? Einloggen'}</button></div></main></div>
 return <div className="app-shell"><main className="phone">
  <header className="topbar"><Logo/><button className="credit-pill" onClick={()=>setScreen('wallet')}>● {credits}</button></header>
  <section className="content">
   {screen==='welcome'&&<div className="welcome"><div className="hero"><img src={heroPhotos[0]}/><div className="hero-shade"></div><div className="hero-brand"><Logo hero/><span>MEET BEYOND MATCHING.</span></div><div className="hero-copy"><span className="eyebrow">ECHT. SPONTAN. ZUSAMMEN.</span><h1>From me<br/>to <em>we.</em></h1><p>Dating, Freundschaft und gemeinsame Erlebnisse in einer App. Nicht ewig swipen – sondern rausgehen.</p></div></div><div className="welcome-actions"><button className="primary" onClick={()=>setScreen('home')}>Was willst du heute? →</button><div className="mini-gallery"><img src={heroPhotos[1]}/><div><b>Mehr echte Momente.</b><span>Vom Drink zu zweit bis zur spontanen Gruppe.</span></div><img src={heroPhotos[2]}/></div><div className="manifesto"><span>ONE</span><i>für dich</i><span>2</span><i>mit jemandem</i><span>US</span><i>gemeinsam</i></div><p className="promise">Keine endlosen Swipes. Kein Abo-Zwang. Entscheide, was du erleben willst – und finde Menschen, die dazu passen.</p></div></div>}
   {screen==='home'&&<><div className="hello"><h1>Hey {session?.user?.user_metadata?.display_name || 'Leon'}! 👋</h1><p>Was willst du heute?</p></div><button className="nearby-banner" onClick={()=>setScreen('live')}><span>◎</span><div><b>Live in deiner Nähe</b><small>Events & Matches auf der Karte entdecken</small></div><strong>→</strong></button><div className="intent-grid">{intents.map(([ic,n])=><button className={intent===n?'selected':''} key={n} onClick={()=>setIntent(n)}><span>{ic}</span>{n}</button>)}</div><h4>ONE, 2 oder US?</h4><div className="mode-grid"><button className={type==='ONE'?'one active':'one'} onClick={()=>setType('ONE')}><b>ONE</b><small>Für mich</small></button><button className={type==='2'?'two active':'two'} onClick={()=>setType('2')}><b>2</b><small>Mit jemandem</small></button><button className={type==='US'?'us active':'us'} onClick={()=>setType('US')}><b>US</b><small>In einer Gruppe</small></button></div><button className="primary" onClick={()=>setScreen('time')}>Weiter</button></>}
   {screen==='live'&&<><div className="page-title"><h1>Live Map</h1><p>Finde Events in deiner Umgebung und – nur mit gegenseitiger Freigabe – deine Matches.</p></div><div className="live-map"><div className="map-grid"></div><div className="map-you">●<span>Du</span></div>{livePeople.slice(0,3).map((p,i)=><div key={p.user_id} className={'map-pin person p'+i}>♡<span>{p.profiles?.display_name||'Match live'}</span></div>)}<div className="map-status">{geo?`Standort aktiv · ± ${Math.round(geo.accuracy)} m`:'Standort noch nicht aktiviert'}</div></div>{geoError&&<div className="location-error">{geoError}</div>}<button className="secondary" onClick={locateMe} disabled={geoBusy}>{geoBusy?'Standort wird gesucht …':'◎ Meinen Standort verwenden'}</button><div className="privacy-card"><div><b>Live-Standort teilen</b><p>Standardmäßig AUS. Nur aktive Matches können dich sehen. Die Freigabe endet automatisch nach 30 Minuten.</p></div><label className="toggle"><input type="checkbox" checked={sharing} onChange={e=>e.target.checked?startSharing():stopSharing()}/><span></span></label><div className="live-options"><label><input type="checkbox" checked={precise} onChange={e=>setPrecise(e.target.checked)}/> Präzisen Standort zeigen</label><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="matches">Nur Matches</option><option value="friends">Nur Freunde</option></select></div></div><h3 className="section-title">Events in deiner Nähe</h3><div className="nearby-list">{visibleEvents.map(e=><button key={e.id||e.title} onClick={()=>{setSelectedEvent(e);setScreen('event')}}><img src={e.img}/><div><b>{e.title}</b><span>{e.meta}</span><small>{e.distance?`◎ ${e.distance}`:'Live Event'}</small></div><strong>{e.price.toFixed(0)} €</strong></button>)}</div><h3 className="section-title">Live sichtbar</h3>{livePeople.length?<div className="live-contacts">{livePeople.map(p=><div key={p.user_id}><img src={p.profiles?.avatar_url||fallbackAvatar}/><span><b>{p.profiles?.display_name||'Match'}</b><small>teilt gerade den Live-Standort</small></span></div>)}</div>:<div className="live-note">Noch keine gegenseitig freigegebenen Live-Standorte. Es werden nur aktive Matches angezeigt, die ihre Position ausdrücklich teilen.</div>}</>}
   {screen==='time'&&<><div className="page-title"><h1>Wann?</h1><p>Sag uns, wann es passt.</p></div><div className="choice-list">{times.map(t=><button className={time===t?'active':''} onClick={()=>setTime(t)} key={t}>{t}</button>)}</div><button className="primary" onClick={()=>setScreen('type')}>Weiter</button></>}
   {screen==='type'&&<><div className="page-title"><h1>Mit wem?</h1><p>Wer passt zu dir?</p></div><div className="choice-list">{matchTypes.map(([k,a,b])=><button className={type===k?'active':''} onClick={()=>setType(k)} key={k}><strong>{k}</strong><span><b>{a}</b><small>{b}</small></span></button>)}</div><button className="primary" onClick={()=>setScreen('matches')}>Menschen entdecken</button></>}
   {screen==='matches'&&<><div className="page-title"><h1>Entdecken</h1><p>{profiles.length?'Echte Profile aus One:2:Us.':'Noch keine weiteren echten Profile – aktuell siehst du Vorschauprofile.'}</p></div><div className="people-grid rich">{discoveryPeople.map(p=><button key={p.id||p.name} onClick={()=>{setSelectedPerson(p);setScreen('person')}}><img src={p.img}/><div><b>{p.name}{p.age?`, ${p.age}`:''}{p.verified?' ✓':''}</b><small>{p.city}</small><strong>{p.match}% Match</strong></div></button>)}</div></>}
   {screen==='person'&&selectedPerson&&<><div className="person-hero"><img src={selectedPerson.img}/><button onClick={()=>setScreen('matches')}>←</button><div><h1>{selectedPerson.name}{selectedPerson.age?`, ${selectedPerson.age}`:''}</h1><p>{selectedPerson.city} · {selectedPerson.match}% Match</p></div></div><div className="person-copy"><p>{selectedPerson.bio}</p><div className="tag-row"><span>{intent}</span><span>{time.split(' · ')[0]}</span><span>{type}</span></div><button className="primary" disabled={backendBusy} onClick={doLike}>Like senden · 1 Credit</button></div></>}
   {screen==='chats'&&<><div className="page-title"><h1>Deine Matches</h1><p>Nur gegenseitige Likes werden hier freigeschaltet.</p></div>{matches.length?<div className="match-list">{matches.map(m=><button key={m.id} onClick={()=>openMatch(m)}><img src={m.person.avatar_url||fallbackAvatar}/><span><b>{m.person.display_name||'Match'}</b><small>{m.person.city||'One:2:Us'} · Chat öffnen</small></span><strong>›</strong></button>)}</div>:<div className="live-note">Noch kein echtes Match. Lege einen zweiten Testnutzer an und liked euch gegenseitig.</div>}</>}
   {screen==='chat'&&<><div className="chat-head"><button className="chat-back" onClick={()=>setScreen('chats')}>‹</button><img src={activeMatch?.person?.avatar_url||fallbackAvatar}/><div><h2>{activeMatch?.person?.display_name||selectedPerson?.name||'Chat'}</h2><span>{otherTyping?'schreibt gerade …':activeMatch?.person?.city||'One:2:Us Match'}</span></div></div><div className="chat-box">{chat.map((m,i)=>{const mine=m.sender_id===session?.user?.id;return <div key={m.id||i} className={'bubble '+(mine?'me':'them')}><div className="bubble-text">{m.body||m.message||m.text}</div><div className="bubble-meta"><span>{chatTime(m.created_at)}</span>{mine&&<span className={m.read_at?'read read-on':'read'}>{m.read_at?'✓✓':'✓'}</span>}</div></div>})}{otherTyping&&<div className="typing-bubble"><i></i><i></i><i></i></div>}</div><div className="chat-input"><input value={chatText} onChange={handleChatInput} onKeyDown={e=>e.key==='Enter'&&sendChatNow()} placeholder="Nachricht schreiben …"/><button onClick={sendChatNow}>↑</button></div></>}
   {screen==='experiences'&&<><div className="page-title"><h1>Events</h1><p>{events.length?'Echte Events aus Supabase.':'Vorschau – echte Events werden aus Supabase geladen.'}</p></div><div className="experience-list rich">{visibleEvents.map(e=><button key={e.id||e.title} onClick={()=>{setSelectedEvent(e);setScreen('event')}}><img src={e.img}/><span><b>{e.title}</b><small>{e.meta}</small></span><strong>{e.price.toFixed(0)} €</strong></button>)}</div></>}
   {screen==='event'&&selectedEvent&&<><div className="event-cover photo" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.75)),url(${selectedEvent.img})`}}><span>ONE NIGHT</span></div><div className="event-detail"><h1>{selectedEvent.title}</h1><p>{selectedEvent.meta}</p>{selectedEvent.description&&<p>{selectedEvent.description}</p>}<p>{selectedEvent.id?'Dieses Event ist live im Backend hinterlegt.':'Vorschau-Event'}</p><button className="primary" onClick={()=>buyEvent(selectedEvent)}>Ich bin dabei! · {selectedEvent.price.toFixed(0)} €</button></div></>}
   {screen==='wallet'&&<><div className="page-title"><h1>Pay per use.</h1><p>Kein Abo. Du zahlst nur, wenn du One:2:Us nutzt.</p></div><div className="balance"><small>Dein Guthaben</small><strong>{credits}</strong><span>Credits</span></div><div className="packs">{[[10,9.9],[25,19.9],[60,39.9]].map(([c,p])=><button key={c} onClick={()=>payCredits(c)}><b>{c} Credits</b><span>{p.toFixed(2).replace('.',',')} €</span></button>)}</div><div className="payment-note"><b>Stripe Checkout</b><p>Apple Pay · Google Pay · Karte</p><small>Nach erfolgreicher Zahlung werden deine Credits automatisch über den Stripe-Webhook verbucht und beim Zurückkehren in die App neu geladen.</small></div>{bookings.length>0&&<div className="booking-note">✓ {bookings.filter(b=>b.payment_status==='paid').length} bezahlte Eventbuchung(en)</div>}</>}
   {screen==='profile'&&<><div className="page-title"><h1>Profil</h1><p>Dein Auftritt entscheidet über gute Matches.</p></div><div className="profile-box"><div className="profile-avatar">{(session?.user?.user_metadata?.display_name||'L')[0]}</div><h2>{session?.user?.user_metadata?.display_name||'Leon'}</h2><p>Account aktiv ✓ · {credits} Credits</p><button className="primary" onClick={signOut}>Ausloggen</button></div><div className="choice-list"><button>Profilbild & Bio ›</button><button>Interessen & Präferenzen ›</button><button onClick={()=>setScreen('live')}>Live-Standort & Sichtbarkeit ›</button><button>Sicherheit & Verifizierung ›</button><button>Datenschutz ›</button></div></>}
  </section>
  <nav className="nav five"><button className={['welcome','home'].includes(screen)?'active':''} onClick={()=>setScreen('welcome')}>⌂<span>Home</span></button><button className={['time','type','matches','person','experiences','event'].includes(screen)?'active':''} onClick={()=>setScreen('matches')}>⌕<span>Entdecken</span></button><button className={screen==='live'?'active':''} onClick={()=>setScreen('live')}>◎<span>Live</span></button><button className={['chats','chat'].includes(screen)?'active':''} onClick={()=>setScreen('chats')}>♡<span>Chats</span></button><button className={screen==='profile'?'active':''} onClick={()=>setScreen('profile')}>♙<span>Profil</span></button></nav>
  {checkout&&<div className="modal"><div><Logo compact/><h2>{checkout.label}</h2><p>{checkout.amount},00 €</p><button className="apple" onClick={confirmPay}> Pay</button><button className="card" onClick={confirmPay}>Demo mit Karte</button><button className="cancel" onClick={()=>setCheckout(null)}>Abbrechen</button><small>Vorschau-Event ohne Backend-ID – es wird kein echtes Geld abgebucht.</small></div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main></div>
}