import { useEffect, useState } from 'react'
import { backendConfigured } from './lib/supabase'
import { getSession, onAuthChange, signIn, signOut, signUp, startCheckout } from './lib/backend'

const intents = [['♡','Date'],['♧','Drink'],['🍴','Dinner'],['♫','Music'],['✣','Move'],['☆','Party'],['✈','Trip'],['♨','Chill'],['●','Event'],['◌','Explore'],['⚽','Sport'],['+','Andere']]
const times = ['Jetzt · In den nächsten 2 Stunden','Heute Abend · Ab 18:00','Dieses Wochenende · Sa–So','Irgendwann · Passt mir zusammen']
const matchTypes = [['ONE','Jemand Besonderes','Date / romantisch'],['2','Neue Freunde','Locker kennenlernen'],['US','Eine Gruppe','Gemeinsam ist besser']]
const people = [{name:'Mara',age:34,match:96},{name:'Tim',age:36,match:92},{name:'Lea',age:33,match:91},{name:'Max',age:35,match:89},{name:'Sara',age:32,match:88},{name:'Ben',age:37,match:86}]
const experiences = [{title:'Cocktail Night',meta:'Heute · 19:30 · 1,2 km',price:19},{title:'Live Konzert',meta:'Heute · 20:00 · 2,1 km',price:24},{title:'Running Crew',meta:'Morgen · 09:00 · 1,5 km',price:9}]
const heroPhotos=['https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=700&q=85']
function Logo({compact=false}) { return <div className={'logo '+(compact?'compact':'')}><span>One</span><i>:</i><b>2</b><i>:</i><span>Us</span></div> }

export default function App(){
 const [screen,setScreen]=useState('welcome'); const [intent,setIntent]=useState('Date'); const [time,setTime]=useState(times[1]); const [type,setType]=useState('ONE'); const [credits,setCredits]=useState(12); const [toast,setToast]=useState(''); const [checkout,setCheckout]=useState(null)
 const [session,setSession]=useState(null); const [authReady,setAuthReady]=useState(!backendConfigured); const [authMode,setAuthMode]=useState('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [displayName,setDisplayName]=useState(''); const [authBusy,setAuthBusy]=useState(false); const [authError,setAuthError]=useState('')
 useEffect(()=>{ if(!backendConfigured)return; getSession().then(s=>{setSession(s);setAuthReady(true)}); const sub=onAuthChange(s=>setSession(s)); return()=>sub.unsubscribe() },[])
 const flash=m=>{setToast(m);setTimeout(()=>setToast(''),1700)}
 const handleAuth=async()=>{setAuthBusy(true);setAuthError('');try{if(authMode==='register'){await signUp(email,password,displayName);flash('Account angelegt.')}else await signIn(email,password)}catch(e){setAuthError(e.message)}finally{setAuthBusy(false)}}
 const pay=async(label,amount)=>{ if(label.includes('Credits')&&backendConfigured&&session){try{await startCheckout('credits',amount)}catch(e){flash(e.message)}return} setCheckout({label,amount}) }
 const confirmPay=()=>{setCredits(v=>v+checkout.amount);flash(`${checkout.amount} Credits gekauft`);setCheckout(null)}
 if(!authReady) return <div className="app-shell"><main className="phone"><div className="auth-card"><Logo compact/><p>Verbindung wird hergestellt …</p></div></main></div>
 if(backendConfigured&&!session) return <div className="app-shell"><main className="phone"><div className="auth-card"><Logo compact/><h1>{authMode==='login'?'Willkommen zurück.':'From me to we.'}</h1><p>{authMode==='login'?'Einloggen und echte Verbindungen finden.':'Erstelle dein One:2:Us Profil.'}</p>{authMode==='register'&&<input placeholder="Dein Name" value={displayName} onChange={e=>setDisplayName(e.target.value)}/>}<input type="email" placeholder="E-Mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Passwort (mind. 6 Zeichen)" value={password} onChange={e=>setPassword(e.target.value)}/>{authError&&<small className="auth-error">{authError}</small>}<button className="primary" disabled={authBusy} onClick={handleAuth}>{authBusy?'Bitte warten …':authMode==='login'?'Einloggen':'Registrieren'}</button><button className="auth-switch" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'Noch kein Konto? Registrieren':'Schon dabei? Einloggen'}</button></div></main></div>
 return <div className="app-shell"><main className="phone">
  <header className="topbar"><Logo/><button className="credit-pill" onClick={()=>setScreen('wallet')}>● {credits}</button></header>
  <section className="content">
   {screen==='welcome'&&<div className="welcome"><div className="hero"><img src={heroPhotos[0]}/><div className="hero-shade"></div><div className="hero-copy"><span className="eyebrow">ECHT. SPONTAN. ZUSAMMEN.</span><h1>From me<br/>to <em>we.</em></h1><p>Dating war gestern. One:2:Us bringt dich mit Menschen zusammen, die heute dasselbe erleben wollen wie du.</p></div></div><div className="welcome-actions"><button className="primary" onClick={()=>setScreen('home')}>Was willst du heute? →</button><div className="mini-gallery"><img src={heroPhotos[1]}/><div><b>Mehr echte Momente.</b><span>Vom Drink zu zweit bis zur spontanen Gruppe.</span></div><img src={heroPhotos[2]}/></div><div className="manifesto"><span>ONE</span><i>für dich</i><span>2</span><i>mit jemandem</i><span>US</span><i>gemeinsam</i></div><p className="promise">Keine endlosen Swipes. Kein Abo-Zwang. Entscheide, was du erleben willst – und finde Menschen, die dazu passen.</p></div></div>}
   {screen==='home'&&<><div className="hello"><h1>Hey {session?.user?.user_metadata?.display_name || 'Leon'}! 👋</h1><p>Was willst du heute?</p></div><div className="intent-grid">{intents.map(([ic,n])=><button className={intent===n?'selected':''} key={n} onClick={()=>setIntent(n)}><span>{ic}</span>{n}</button>)}</div><h4>ONE, 2 oder US?</h4><div className="mode-grid"><button className={type==='ONE'?'one active':'one'} onClick={()=>setType('ONE')}><b>ONE</b><small>Für mich</small></button><button className={type==='2'?'two active':'two'} onClick={()=>setType('2')}><b>2</b><small>Mit jemandem</small></button><button className={type==='US'?'us active':'us'} onClick={()=>setType('US')}><b>US</b><small>In einer Gruppe</small></button></div><button className="primary" onClick={()=>setScreen('time')}>Weiter</button></>}
   {screen==='time'&&<><div className="page-title"><h1>Wann?</h1><p>Sag uns, wann es passt.</p></div><div className="choice-list">{times.map(t=><button className={time===t?'active':''} onClick={()=>setTime(t)} key={t}>{t}</button>)}</div><button className="primary" onClick={()=>setScreen('type')}>Weiter</button></>}
   {screen==='type'&&<><div className="page-title"><h1>Mit wem?</h1><p>Wer passt zu dir?</p></div><div className="choice-list">{matchTypes.map(([k,a,b])=><button className={type===k?'active':''} onClick={()=>setType(k)} key={k}><strong>{k}</strong><span><b>{a}</b><small>{b}</small></span></button>)}</div><button className="primary" onClick={()=>setScreen('matches')}>Matches finden · 1 Credit</button></>}
   {screen==='matches'&&<><div className="page-title"><h1>Deine Matches</h1><p>Passende Menschen für {intent}.</p></div><div className="people-grid">{people.map(p=><button key={p.name} onClick={()=>flash(`${p.name} ausgewählt`)}><div className="person">{p.name[0]}</div><b>{p.name}, {p.age}</b><small>{p.match}% Match</small></button>)}</div><button className="primary" onClick={()=>{if(credits<1)return setScreen('wallet');setCredits(v=>v-1);setScreen('experiences')}}>Vorschläge anzeigen · 1 Credit</button></>}
   {screen==='experiences'&&<><div className="page-title"><h1>Vorschläge für dich</h1><p>{intent} · {time.split(' · ')[0]}</p></div><div className="experience-list">{experiences.map(e=><button key={e.title} onClick={()=>setScreen('event')}><div className="event-img">✦</div><span><b>{e.title}</b><small>{e.meta}</small></span><strong>{e.price} €</strong></button>)}</div></>}
   {screen==='event'&&<><div className="event-cover">ONE NIGHT</div><div className="event-detail"><h1>Cocktail Night</h1><p>Heute · 19:30<br/>Lübeck · 1,2 km</p><p>5 Personen gehen hin</p><div className="avatars">● ● ● ● ●</div><button className="primary" onClick={()=>pay('Cocktail Night Ticket',19)}>Ich bin dabei! · 19 €</button></div></>}
   {screen==='wallet'&&<><div className="page-title"><h1>Pay per use.</h1><p>Kein Abo. Du zahlst nur, wenn du One:2:Us nutzt.</p></div><div className="balance"><small>Dein Guthaben</small><strong>{credits}</strong><span>Credits</span></div><div className="packs">{[[10,9.9],[25,19.9],[60,39.9]].map(([c,p])=><button key={c} onClick={()=>pay(`${c} Credits`,c)}><b>{c} Credits</b><span>{p.toFixed(2).replace('.',',')} €</span></button>)}</div><div className="payment-note"><b>Sichere Zahlung</b><p>Apple Pay · Google Pay · Karte</p><small>{backendConfigured?'Stripe Checkout ist vorbereitet. Nach Einrichtung der Supabase Edge Functions werden Zahlungen serverseitig verbucht.':'Demo-Modus – Backend-Variablen fehlen noch.'}</small></div></>}
   {screen==='profile'&&<><div className="page-title"><h1>Profil</h1><p>Sicher & respektvoll.</p></div><div className="profile-box"><div className="profile-avatar">{(session?.user?.user_metadata?.display_name || 'L')[0]}</div><h2>{session?.user?.user_metadata?.display_name || 'Leon'}</h2><p>{session?'Account aktiv ✓':'Demo-Profil'}</p>{session&&<button className="primary" onClick={signOut}>Ausloggen</button>}</div><div className="choice-list"><button>Sicherheit & Verifizierung ›</button><button>Dating-Präferenzen ›</button><button>Datenschutz ›</button><button>Blockieren & Melden ›</button></div></>}
  </section>
  <nav className="nav"><button className={['welcome','home'].includes(screen)?'active':''} onClick={()=>setScreen('welcome')}>⌂<span>Home</span></button><button className={['time','type','matches','experiences','event'].includes(screen)?'active':''} onClick={()=>setScreen('matches')}>⌕<span>Entdecken</span></button><button onClick={()=>flash('Chats sind nach Match kostenlos')}>♡<span>Chats</span></button><button className={screen==='profile'?'active':''} onClick={()=>setScreen('profile')}>♙<span>Profil</span></button></nav>
  {checkout&&<div className="modal"><div><Logo compact/><h2>{checkout.label}</h2><p>{checkout.amount===19?'19,00 €':'Credit-Paket kaufen'}</p><button className="apple" onClick={confirmPay}> Pay</button><button className="card" onClick={confirmPay}>Mit Karte bezahlen</button><button className="cancel" onClick={()=>setCheckout(null)}>Abbrechen</button><small>{backendConfigured?'Event-Zahlung folgt nach Anlage der echten Event-ID.':'Demo-Zahlung – es wird kein echtes Geld abgebucht.'}</small></div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main></div>
}